In [10]:
import numpy as np

In [17]:
#1-DArray
arr1 = np.array([2,3,4,6,5])
print("Array 1:",arr1)

arr2 = np.array([2,3,5,3,34])
print("Array 2:",arr2)

arr3 =arr1*arr2
print()
print("Array 3:",arr1)

Array 1: [2 3 4 6 5]
Array 2: [ 2  3  5  3 34]

Array 3: [2 3 4 6 5]


In [14]:
print("Array 3:",arr1)

Array 3: [2 3 4 6 5]


In [42]:
#2-DArray and multiplication
arr4 =np.array([[1,2,3],
                [2,3,4],
                [5,6,7]])
print("Array 4:\n",arr4)
print()
arr5 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Array 5:\n",arr5)
arr6 = arr4+arr5 
#simple Addition
print()
print("Array 6: Addition of Array 4 and Array 5 \n",arr6)
arr7 = arr4*arr5
#simple multiplication 
print("Array 7: Multiplication of Array 4 and Array 5\n",arr7)

Array 4:
 [[1 2 3]
 [2 3 4]
 [5 6 7]]

Array 5:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 6: Addition of Array 4 and Array 5 
 [[ 2  4  6]
 [ 6  8 10]
 [12 14 16]]
Array 7: Multiplication of Array 4 and Array 5
 [[ 1  4  9]
 [ 8 15 24]
 [35 48 63]]
