In [1]:
import numpy as np

In [11]:
# 1-d array
arr1 = np.array([1, 3, 5, 6, 2])
arr

arr2 = np.array([2, 4, 7, 6, 8])
arr2

arr1 *= arr2 # arr1 = arr1 * arr2
print(arr1)

[ 2 12 35 36 16]


In [21]:
# 2-d array and multiplication

arr3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr4 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr5 = arr3 + arr4
arr6 = arr3.dot(arr4)

print(arr5)
print()
print(arr6)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [22]:
# array dimension

print(arr1.ndim)
print(arr3.ndim)

1
2


In [25]:
# to declare dimensions dynamically
arr7 = np.array([1, 3, 5, 6, 2], ndmin=4)
arr7

array([[[[1, 3, 5, 6, 2]]]])

In [42]:
#array slicing

arr8 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr8[1:5])
print(arr8[4:])
print(arr8[:4])
print(arr8[-3:-1])
print(arr8[1:5:2])
print(arr8[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [51]:
arr9 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr9[0, 1:4], "\n")
print(arr9[1, 1:4], "\n")
print(arr9[0:2, 3], "\n")  #from both element select index 2 [Selement:Eelement, Sindex:Eindex]
print(arr9[0:2, 1:4], "\n")

[2 3 4] 

[7 8 9] 

[4 9] 

[[2 3 4]
 [7 8 9]] 

